services:
  alie-frontend:
    image: harbor.alie.javeriana.edu.co/images/alie-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 4200:4000
    expose:
      - 4000
