apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: alie-frontend
  name: alie-frontend
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 4000
  selector:
    io.kompose.service: alie-frontend
