apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: alie-frontend
  name: alie-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alie-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: alie-frontend
    spec:
      containers:
        - image: harbor.alie.javeriana.edu.co/images/alie-frontend:latest
          name: alie-frontend
          ports:
            - containerPort: 4000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
